### ISSUE TITLE
Экспорт в DER кодировку для криптопро.

### ISSUE THREAD

**Issue by russeljo** [Aleksandr-ru/RusCryptoJS#10]
readCertificate  для криптопро возвращает в base64 кодировке.
Есть ли возможность сделать экспорт в DER кодировке? Или как-то перекодировать base64->DER?

**Comment by Aleksandr-ru** [comment]
Крипто-про не поддерживает бинарные данные (DER) в вебе.
Для перекодировки в вебе можно использовать [atob](https://developer.mozilla.org/ru/docs/Web/API/atob), но работать с бинарными данными в вебе не самая лучшая идея.
Вне браузера корректно использовать `openssl x509 -inform der -in CERTIFICATE.der -out CERTIFICATE.pem`
