### ISSUE TITLE
Проблема с IE 11

### ISSUE THREAD

**Issue by russeljo** [Aleksandr-ru/RusCryptoJS#12]
IE 11 не поддерживает стрелочные функции и let

**Comment by Aleksandr-ru** [comment]
это известный факт. в чем именно ваша проблема?

**Comment by russeljo** [comment]
Проблема в IE запустить

**Comment by Aleksandr-ru** [comment]
по опыту внедрений библиотека прекрасно работает в ие.
опишите подробнее что пытаетесь сделать и что не получается?

**Comment by russeljo** [comment]
Ругается "Предполагается наличие ':'" на этот код, например:
```
 var attached = inputAttached.checked;
return cryptopro.signData(data, thumbprint, {attached} );
```

**Comment by Aleksandr-ru** [comment]
что это за код? откуда?

ЗЫ если вы пытаетесь работать с демо страницей https://aleksandr-ru.github.io/RusCryptoJS/cryptopro.html в ие, то она там работать не будет (в отличие от самой библиотеки)

**Comment by russeljo** [comment]
Да, код взят отсюда, строка 90
https://aleksandr-ru.github.io/RusCryptoJS/js/cryptopro.js 

Подскажите, как этот код изменить, чтобы в ИЕ заработало?

**Comment by russeljo** [comment]
Ругается на { attached }, как понимаю там необходимо название свойства дописать?

**Comment by Aleksandr-ru** [comment]
вам нужно либо переписать свой код с учетом всех особенностей ие, либо использовать что-то вроде [babel](https://en.wikipedia.org/wiki/Babel_(transcompiler)), чтоб он сделал ваш код ие-пригодным.

**Comment by russeljo** [comment]
Подскажите как корректно задать третий параметр для
`cryptopro.signData(data, thumbprint, { attached });`

В вашем примере

```

var inputAttached = document.getElementById('attached');

function signData() {
    inputSign.value = '';
    var cryptopro = new window.RusCryptoJS.CryptoPro;
    var data = btoa(inputData.value);
    var attached = inputAttached.checked;
    var thumbprint = inputCertId.value;
    return cryptopro.init().then(info => {
        console.log('Initialized', info);
        return cryptopro.signData(data, thumbprint, { attached });
    }).then(sign => {
        inputSign.value = sign;
        return cryptopro.verifySign(data, sign, { attached }).catch(e => {
            console.warn(e);
            return false;
        });
    })
    .then(verified => {
        console.log('Verified: ', verified);
        alert('Success!');
    }).catch(e => {
        alert('Failed! ' + e);
    });
}
```

**Comment by Aleksandr-ru** [comment]
попробуйте задать явно `{attached: true|false}` или опустить вовсе, в зависимости от того, какую подпись хотите получить

и не сочтите за труд почитать документацию https://aleksandr-ru.github.io/RusCryptoJS/cryptopro.html#signData 
это снимет много вопросов.

**Comment by russeljo** [comment]
Спасибо! 

```
var options = {
    pin : "...",
    attached : true 
};

cryptopro.signData(data, thumbprint, options);
```
