### ISSUE TITLE
Oid способ идентификации

### ISSUE THREAD

**Issue by Waiker** [Aleksandr-ru/RusCryptoJS#13]
Приветствую. 
Обратил внимание что не хватает oid 1.2.643.100.114.

[Описание КриптоПро](https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/349/19/nstrojjk-kriptopro-uc-v-sootvetstvii-s-izmenenijami-795-prikz-fsb)

[ФСБ 795 ст.3 п.28.1](http://www.consultant.ru/document/cons_doc_LAW_378767/1d48783d6d6cb9252b2d9c5340fff6e7b4520a3f/#dst100062)

**Comment by Aleksandr-ru** [comment]
где не хватает?

**Comment by Waiker** [comment]
смотрю по созданному запросу

**Comment by Aleksandr-ru** [comment]
В запросе его и не должно быть!
Даже в вашей ссылке написано `Настройка данного расширения выполняется на сервере ЦС` и подробно описан процесс настройки шаблонов выпуска сертификатов в УЦ.

Вы, конечно, можете попробовать руками добавить его в запрос на сертификат, но это должен делать УЦ, выпускающий сертификат.

**Comment by Waiker** [comment]
УЦ требуют указывать данный oid в csr. Попробовал добавить его в параметры строки DN - не помогает.
Пример валидного csr в моем случае ниже. Прошу подсказать как указать необходимый oid в том-же месте. 
![oid114](https://user-images.githubusercontent.com/5464086/144836575-a71ac567-6ab7-4f6c-a750-3c1d9b4ed1e4.png)

**Comment by Aleksandr-ru** [comment]
согласно вашей инструкции этот OID добавляется в шаблоне на самом УЦ и по смыслу - это задача УЦ, выпускающего сертификат, а не того, кто формирует запрос на сертификат.
технически, возможно, можно добавить этот OID в создаваемый запрос на сертификат аналогично другип параметрам, но для этого ваш СКЗИ должен его поддерживать.
За настройками скзи обратитесь к производителю.

Если вы хотите именно руками опционально добавлять еще одно расширение к сертификату, если я правильно вижу из вашей картинки, то такого функционала в библиотеке нет, библиотек добавляет только KeyUsage, EnhancedKeyUsage, SubjectSignTool. Остальное на совести скзи.
