### ISSUE TITLE
подпись XMLDSIG

### ISSUE THREAD

**Issue by codegenz** [Aleksandr-ru/RusCryptoJS#14]
В связи с введением МашиноЧитаемых Доверенностей и требованием подписывать их в формате XMLDSIG, планируется ли поддержка этого формата в Вашей библиотеке?

**Comment by Aleksandr-ru** [comment]
Нет не планируется тк не поддерживается большинством веб-плагинов. 

Вообще, внедрение подписей в XML - это не задача для клиентского веб плагина. На клиенте должно происходить только формирование ЭП, а формирование XML с полученной подписью - это уже задача серврерного ПО.
