### ISSUE TITLE
Данные сертификата из подписи

### ISSUE THREAD

**Issue by Waiker** [Aleksandr-ru/RusCryptoJS#16]
У вас есть функция verifySign, подскажите как получить данные о сертификате/тах в отсоединенной подписи?

**Comment by Aleksandr-ru** [comment]
в разных скзи по-разному и не у всех это можно в веб. в моей библиотеке такого функционала нет тк в клиент-серверном взаимодействии все работа с сертификатом, содержащимся в подписи, должна производится на сервере

**Comment by Waiker** [comment]
Спасибо. Реализовал разбор сертификата на беке на php.
