### ISSUE TITLE
Nuxt: 500 window is not defined

### ISSUE THREAD

**Issue by symbyozis** [Aleksandr-ru/RusCryptoJS#17]
Добрый день. Как заставить работать плагин на NuxtJS? 
<img width="1008" alt="image" src="https://github.com/Aleksandr-ru/RusCryptoJS/assets/25963025/11d4fff4-5762-492d-a0d2-14e7d196e00b">

**Comment by Aleksandr-ru** [comment]
библиотека и все плагины которые она использует должны выполняться в контексте браузера, а не на бекенде.
