### ISSUE TITLE
Не все сертификаты

### ISSUE THREAD

**Issue by andy-scboy** [Aleksandr-ru/RusCryptoJS#18]
https://github.com/Aleksandr-ru/RusCryptoJS/blob/76a56eb7f19206c39eae119e2d5aaf03335de5cd/src/RuToken/index.js#L364
Здесь просматриваются только пользовательские сертификаты. На Rutoken сертификат может быть записан куда угодно есть еще категории:
CERT_CATEGORY_CA
CERT_CATEGORY_OTHER
CERT_CATEGORY_UNSPEC

**Comment by Aleksandr-ru** [comment]
да и так не только в рутокене. библиотека предназначена для выпуска и работы с сертификатами пользователя, а не уц и прочими.
