### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by alekseykurylev** [Aleksandr-ru/RusCryptoJS#19]
В NextJS пр объявлении `new CryptoPro()` внутри `useEffect()` ошибка `window is not defined`. 
Объект `window` в `useEffect` доступен.

```tsx
'use client'

import {useEffect, useState} from "react";
import { CryptoPro, CertListItemInterface } from 'ruscryptojs';

export default function Home() {
  const [certs, setCerts] = useState<CertListItemInterface[]>([]);

  useEffect(() => {
    const cryptopro = new CryptoPro();
    const listCertificates = async () => {
      await cryptopro.init();
      const list = await cryptopro.listCertificates();
      setCerts(list)
    };
    listCertificates().catch((error) => {
      console.log(error);
    });
  }, []);

  return <div>{certs.map((item) => <div key={item.id}>{item.name}</div>)}</div>
}
```

**Comment by Aleksandr-ru** [comment]
по обрывку кода невозможно понять как устоено ваше приложение и я не представляю, что под каптом у вашего фремворка.

с уверненостью можно сказать только то, что компилятор явно не согласен с утвержденеим про 
> Объект window в useEffect доступен.

с наибольшей вероятностью, проблема в вашем приложении, и помощи вам в первую очередь надо искать в камьюнити фреймворка, а не здесь.

да и с учетом того, что nextjs ориентирован на серверный рендериг, вполне возможно, что ваша проблема схожа с https://github.com/Aleksandr-ru/RusCryptoJS/issues/17
