### ISSUE TITLE
Подпись не действительна

### ISSUE THREAD

**Issue by Waiker** [Aleksandr-ru/RusCryptoJS#2]
Спасибо за ваш проект. Использую функцию addSign, в параметр dataBase64 даю хеш документа в base64, но при проверке подписи допустим на https://www.justsign.me/verifyqca/Verify/ получаю ошибку.
Здесь тоже ошибка при проверке https://www.gosuslugi.ru/pgu/eds/
![image](https://user-images.githubusercontent.com/5464086/50703150-099ccd80-1075-11e9-9b16-9619e4153649.png)

Например для текстового документа *.txt с содержанием **123321** получаю хеш **MTIzMzIx**
а подпись сохраняю в файле формата *.sig, может быть я что-то делаю неверно. 
Для подписи использую действующий квал. серт. по 2001 ГОСТ. 
С Уважением, Waik.

**Comment by Aleksandr-ru** [comment]
В dataBase64 надо передавать не хэш, а данные (т.е. тело документа)
см. документацию https://aleksandr-ru.github.io/RusCryptoJS/cryptopro.html#addSign
Сторонние сервисы не являются показателем правильной проверки, при проверке подписи утилитой из комплекта крипто-про какой результат?

**Comment by Waiker** [comment]
Спасибо. Поместил  dataBase64  содержимое файла из примера выше (123321) и потом подпись сравнил с *.txt файлом, проверка успешна. Но какие данные передавать в dataBase64  если допустим хочу подписать изображение? 

p/s сервис  https://www.justsign.me/verifyqca/Verify/ это офф. сервис от КриптоПро

**Comment by Aleksandr-ru** [comment]
В dataBase64 нужно поместить тело файла закодированное в base64 (все так же как и с обычной подписью)

**Comment by Waiker** [comment]
Не работает. Использую вашу тестовую страницу проекта, функцию signData();
Для теста беру изображение [Google Logo](https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)

Base64 получаю с помощью FileApi

>               <script>
>                                       var openFile = function (event) {
>                                           fileContent = undefined;
>                                           var input = event.target;
>                                           var reader = new FileReader();
>                                           reader.readAsDataURL(input.files[0]);
>                                           reader.onload = function () {
>                                               var header = ";base64,";
>                                               var fileData = reader.result;
>                                               fileContent = fileData.substr(fileData.indexOf(header) + header.length);
>                                           };
>                                       };
>               </script>

данные из fileContent передаю в параметр dataBase64 функции signData(), после проверяю подпись с помощью криптоАРМ и прочих сервисов, нигде проверка не проходит. 

p/s разобрался, данные из inputa потом кодируются еще раз в base64 выходит один лишний цикл шифрования.  А я сразу помещал туда base64. 
Строка 99 файла cryptopro.js. 
> var data = btoa(inputData.value)

p/s/2 Подскажите еще пожалуйста, насколько я понимаю ваша проект делает только открепленные подписи? Возможности сделать прикрепленную нет?

**Comment by Aleksandr-ru** [comment]
Хорошо что разобрались. Демо пример нацелен показать возможность шифрования текста, чтоб не заставлять потребителя руками кодировать в base64 при работе с веб интерфейсом примера.

Штатно возможность делать прикрепленную подпись не предоставляется тк этот фунуционал низко востребован, да и работа с документом с присоединенной подписью без СКЗИ далее не возможна.

**Comment by Waiker** [comment]
Спасибо. Отписал вам в форму обратной связи на вашем сайте насчет личного вопроса.
С уважением, Waiker/
