### ISSUE TITLE
Failed! Error: Внутренняя ошибка. (0x80070026)

### ISSUE THREAD

**Issue by Cleverscript** [Aleksandr-ru/RusCryptoJS#20]
Здравствуйте Александр, просьба помочь разобраться с проблемой при установке сертификата

Почему то при нажатии на кнопку "ЗАПИСАТЬ СЕРТИФИКАТ" получаю ошибку
![Screenshot_20240704_164554](https://github.com/Aleksandr-ru/RusCryptoJS/assets/204266/2431a04a-f008-4b6e-947a-87215a3b0b73)

Корневой сертификат брал отсюда
https://www.cryptopro.ru/certsrv/certcarc.asp
![Screenshot_20240704_173456](https://github.com/Aleksandr-ru/RusCryptoJS/assets/204266/57c40dd9-978d-4bfa-b7be-f64c9487a8fd)
![Screenshot_20240704_174439](https://github.com/Aleksandr-ru/RusCryptoJS/assets/204266/6859795e-1d67-43ae-9e53-c99d86c10bd4)

OS Linux - Ubuntu 22.04 
Браузер Google Chrome - Версия 125.0.6422.141 (Официальная сборка), (64 бит)

КриптоПро CSP ставил с такими пакетами
![image](https://github.com/Aleksandr-ru/RusCryptoJS/assets/204266/1b1ac995-4a99-43b4-ae07-8f30e47896d4)

По такой инструкции
[Linux КриптоПро CSP.pdf](https://github.com/user-attachments/files/16105826/Linux.CSP.pdf)

Как то можно понять причину этой ошибки?

**Comment by Aleksandr-ru** [comment]
0x80070026 - это ответ от "черного ящика" крпипто про, что за ним стоит неизвестно. гугл и форум крипто про вам в помощь, там вам скорее смогут помочь.

в теории это может быть связано с даннвми, которые сгенерил вам уц, попробуйте запросить сертификат с другим csr и если ситуация сохранится переустановить криптопро.

**Comment by Cleverscript** [comment]
Пришлось отдельно доустановить пакеты для плагина, висел в статусе "плагин не доступен". А также сертификат нужно  в вашу форму вставлять 

Из полученного ответа от УЦ убрать служебные заголовки.
 только base64 данные, между
-----BEGIN CERTIFICATE-----
и
-----END CERTIFICATE-----

https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=23339

**Comment by Aleksandr-ru** [comment]
> Из полученного ответа от УЦ убрать служебные заголовки.
> только base64 данные, между

об этом явно сказано в [документации](https://aleksandr-ru.github.io/RusCryptoJS/cryptopro.html#writeCertificate) и в [инструкции](https://aleksandr.ru/blog/vipusk_testovih_sertifikatov_ep_kriptopro_s_lyubimi_dannimi).
