### ISSUE TITLE
Есть ли возможность декодировать данные с помощью подписи?

### ISSUE THREAD

**Issue by Academior** [Aleksandr-ru/RusCryptoJS#4]
Спасибо за либу!

Скажите пожалуйста, есть ли возможность декодировать строку dataBase64 с помощью подписи? Можно ли каким-то образом вытащить приватный ключ?

**Comment by Aleksandr-ru** [comment]
`dataBase64` это и так не кодированные данные, а те которые мы подписываем (или валидируем). С помощью подписи можно проверить ее валидность относительно данных (ну или валидность данных относительно подписи) методом `verifySign`.  
Подпись содержит отпечаток публичного ключа который используется для валидации.

Для того чтобы вытащить приватный ключ нужен доступ к носителю ключевого контейнера, с помощью которого была создана подпись, это просто в случае крипто-про и контейнеров на файловой системе (опять же если есть доступ к ФС) и весьма сложно в случае носителей с неизвлекаемым контейнером (например jacarta).
