### ISSUE TITLE
Перестала работать подпись CryptoPro

### ISSUE THREAD

**Issue by santieee** [Aleksandr-ru/RusCryptoJS#5]
При попытке подписать что либо выпадает ошибка: 
Failed! Error: Invalid type specified. (0x8009000A)
![photo_2020-02-14_11-52-06](https://user-images.githubusercontent.com/47738087/74515881-793fe600-4f20-11ea-8cb7-c08d0000ec19.jpg)

**Comment by Aleksandr-ru** [comment]
После чего перестала?
Какая ОС, браузер, версия крипто-про?
Какие данные пытаетесь подписать? У вас на скрине походе что-то base64, это лишнее в данном примере.
Не подписывает вообще или только повторно?

**Comment by santieee** [comment]
Проблема была в том что Chrome не мог обновится по какой то причине, переустановка Chrome все исправило. Прошу прощение за беспокойство и большая благодарность за труды.
