### ISSUE TITLE
формат файла base64 подписи

### ISSUE THREAD

**Issue by FantasyNitroGEN** [Aleksandr-ru/RusCryptoJS#6]
Разрешите очень глупый вопрос, в какой формат файла можно выгрузить base64 подпись после ее создания через signData для проверки через сторонние средства.

**Comment by Aleksandr-ru** [comment]
То что вы получаете в результате signData - это PKCS#7 сообщение (см. [RFC 2315](https://tools.ietf.org/html/rfc2315)). Ближе всего это к формату PEM или P7B, только без `----- BEGIN ... END`.
