### ISSUE TITLE
Получение информации из сертификата

### ISSUE THREAD

**Issue by pecheneg2015** [Aleksandr-ru/RusCryptoJS#8]
Добрый день. Посмотрел код,  описание апи КриптоПро,но как то не нашел информации о том, есть ли возможность получить информацию о сертификате из файла  .cer/.crt. Не сталкивались с таким кейсом при разработке библиотеки?

**Comment by Aleksandr-ru** [comment]
> сертификате из файла .cer/.crt.

библиотека работает с установленными сертификатами, доступ к файлам на ФС не предусмотрен моделью безопасности веб приложений, поэтому вы можете попробовать загрузить тело сертификата через FileApi и дальше воспользоваться функционалом разбора X509, которые предоставляет MS Crypto Api в рамках методов крипто-про (см. их документацию)
