### ISSUE TITLE
Считывание сертификатов с usb

### ISSUE THREAD

**Issue by lemonspb** [Aleksandr-ru/RusCryptoJS#9]
Привет, подскажите пожалуйста, есть ли возможность считать сертификаты с usb ?
по идеи должна помочь констатна CAPICOM_SMART_CARD_USER_STORE = 4,
но нет.

**Comment by Aleksandr-ru** [comment]
если вы говорите о крипто-про, то сертификат должен быть установлен в вашем СКЗИ (при этом ключевой контейнер можно оставить на флешке)
в юникс-подобных для доступа веб плагина крипто-про к таким сертификатам их требуется абсорбировтаь 
вот [тут](https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=94678#post94678) почитайте похоже на вашу проблему

**Comment by lemonspb** [comment]
я имею в виду что в на тестовой странице https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_t_sample.html
я могу видеть все сертификаты и установленные на пк и на флешке.  Мне же доступны только сертификаты установленные на пк

**Comment by Aleksandr-ru** [comment]
с этого надо было начинать ) 

https://www.cryptopro.ru/sites/default/files/products/cades/demopage/Code.js
```
    //В версии плагина 2.0.13292+ есть возможность получить сертификаты из 
    //закрытых ключей и не установленных в хранилище
    try {
        oStore.Open(cadesplugin.CADESCOM_CONTAINER_STORE);
        certCnt = oStore.Certificates.Count;
        for (var i = 1; i <= certCnt; i++) {
            var cert = oStore.Certificates.Item(i);
            //Проверяем не добавляли ли мы такой сертификат уже?
```

и

https://www.cryptopro.ru/sites/default/files/products/cades/demopage/async_code.js
```
        //В версии плагина 2.0.13292+ есть возможность получить сертификаты из 
        //закрытых ключей и не установленных в хранилище
        try {
            yield oStore.Open(cadesplugin.CADESCOM_CONTAINER_STORE);
            certs = yield oStore.Certificates;
            certCnt = yield certs.Count;
            for (var i = 1; i <= certCnt; i++) {
                var cert = yield certs.Item(i);
                //Проверяем не добавляли ли мы такой сертификат уже?
                var found = false;
```

эти новые вводные будут реализованы в будущих версиях

**Comment by lemonspb** [comment]
спасибо, именно это и было нужно!
